# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Thread-Rand
version:      0.06
version_from: lib/Thread/Rand.pm
installdirs:  site
requires:
    load:                          0
    Thread::Tie:                   0.09

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
